name: practice

on: 
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name:  make a directory
        run: mkdir hello