name: practice

on: 
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name:  make a directory
        run: mkdir hello

      - name: Create directory and file
        run: |
          mkdir hlo
          echo "Hello!" > hlo/hello.txt

      - name: Upload directory
        uses: actions/upload-artifact@v4
        with:
          name: hlo-folder
          path: hlo/
